### ISSUE TITLE
No issue but

### ISSUE THREAD

**Issue by Lord3n20** [onefuncman/the-most-unexpected-project-ever#2]
I just want to make a Discordbot in COBOL too.

**Comment by onefuncman** [comment]
We have a working prototype that we haven't uploaded to GitHub yet, we were intending to put it over at https://github.com/whatweretheythinking/the-most-unexpected-project-ever/issues though

in the interest of getting things working to iterate more quickly, the architecture right now is using the javascript SDK that handles receiving and sending data to/from Discord and it shells out to Cobol with the commands to execute

**Comment by onefuncman** [comment]
OK, we did a code drop of the current state here: https://github.com/whatweretheythinking/the-most-unexpected-project-ever
